from_latest_tag = true
ignore_merge_commits = true
generate_mono_repository_global_tag = true
branch_whitelist = []
pre_bump_hooks = [
    "git tag v{{version}}",
    "git tag sdk/v{{version}}"
]
post_bump_hooks = [
    "git push --tags",
    "git push origin {{version}} --tags",
]

[changelog]
path = "CHANGELOG.md"
authors = [
    { signature = "Marc Ende", username = "eBeyond" },
]

[git_hooks.commit-msg]
script = """#!/bin/sh
set -e
echo "[Check current commit message]"
cog verify --file $1

echo "[Conventional commit check]"
cog check

echo "[Lints]"
flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
flake8 . --count --exit-zero --statistics
"""

# Or file path
[git_hooks.pre-push]
path = "hooks/pre-push.sh"